% -------------------------------------------------------------------
%  Generated by MATLAB on 5-Jan-2018 18:27:42
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

A = saveVarsMat.A; % <1x1434 double> too many elements

ans = 'double';

bracket_2_3_joint = saveVarsMat.bracket_2_3_joint; % <1x1 table> unsupported class

bracket_2_3_joint_array = saveVarsMat.bracket_2_3_joint_array; % <1434x1 double> too many elements

data = saveVarsMat.data; % <1x1 table> unsupported class

torque = saveVarsMat.torque; % <1x1 timeseries> unsupported class

tout = saveVarsMat.tout; % <1014x1 double> too many elements

var = saveVarsMat.var; % <1x1 struct> too many elements at var.time

clear saveVarsMat;
